#api call for listing all employees
###
GET http://127.0.0.1:8000/employees/
Accept: application/json

#api call for create employee
###
POST http://127.0.0.1:8000/employees/
Content-Type: application/json

{
    "name":"Hari",
    "department":"sales",
    "salary":35000,
    "location":"Thrissur",
    "email":"hari@1234"
}

#api call for retrieving employee
###
GET http://127.0.0.1:8000/employees/1/
Accept: application/json

#api call for deleting employee
###
DELETE http://127.0.0.1:8000/employees/3/
Accept: application/json